### ISSUE TITLE
Proxy.create - Proxy is not defined

### ISSUE THREAD

**Issue by dudeinamotorhome** [Doridian/BeamBot#1]
Just learning Node.JS. Still got a lot to go. What would be causing this? Or Have you seen this error before? I thought looking at some existing code might help me learn and I am on Beam, so...
All the code I have looked at so far, looks ok. But with me being a noob with node.js, I am probably missing something.

/home/pi/dev/beambot-edited/BeamBot/app_bot.js:14
var api = Proxy.create({
          ^
ReferenceError: Proxy is not defined
    at Object.<anonymous> (/home/<user>/BeamBot/app_bot.js:14:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

**Comment by Doridian** [comment]
What command are you using to start the bot?
The correct command is `npm start`

**Comment by dudeinamotorhome** [comment]
Yea, I was running node npm app.js. That was the problem. Thanks for the help.
